# Generated by Django 5.1.7 on 2025-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_college',
            new_name='student_course',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_roll',
            field=models.CharField(max_length=12),
        ),
    ]
