# Generated by Django 5.1.7 on 2025-03-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_college_student_student_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_roll',
            new_name='student_phone_number',
        ),
    ]
