# Generated by Django 5.1.7 on 2025-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_student_roll_student_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='abc@abc.com', max_length=254),
            preserve_default=False,
        ),
    ]
